version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "5204:80"
      - "7074:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PartsDb=Host=db;Database=partsdb;Username=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - wasm-network

  client:
    build:
      context: .
      dockerfile: src/Client/Dockerfile
    ports:
      - "5202:80"
    depends_on:
      - api
    networks:
      - wasm-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=partsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wasm-network

volumes:
  postgres_data:

networks:
  wasm-network:
    driver: bridge